Readme for native cloud functionality
wildfly-extras/sunstone pull request #136
Opened 2023-01-27 11:29 UTC by istraka

Fixes #135

2023-01-30 15:01 UTC, LittleJohnII requested changes

2023-01-30 15:01 UTC, LittleJohnII commented on Azure-README.md
> +Domain mode is not supported - EAP on web app is currently running only in stdandalone mode.
"standalone"

2023-01-31 08:29 UTC, istraka commented on README.md
> +WildFly deploy operation is specific to the type of resources WildFly is running on. The archive that you want to be deployed, you must use `@Deployment` annotation on a static method returning the a
It is a local file. I will add the info.

2023-01-31 11:29 UTC, istraka commented on Aws-README.md
> +},
I will reformate it.

2023-01-31 11:32 UTC, istraka commented on Aws-README.md
> +`mytemplate.yaml` is located in resources. If you wish to share cloud resources among multiple test classes, set `perSuite` parameter to true, include such test classes in a JUnit5 suite and run the
Yes, I will add the info.

2023-01-31 11:35 UTC, istraka commented on Aws-README.md
> +        mode = EapMode.STANDALONE,
Not sure honestly. WildFly makes more sence here, I will change it.

2023-01-31 11:40 UTC, istraka commented on Azure-README.md
> +`mytemplate.yaml` is located in resources. If you wish to share cloud resources among multiple test classes, set `perSuite` parameter to true, include such test classes in a JUnit5 suite and run the
Yes. Logic is same for all cloud deployment annotations

2023-01-31 11:56 UTC, istraka commented on Aws-README.md
> +        mode = EapMode.STANDALONE,
I will address it in https://github.com/wildfly-extras/sunstone/issues/139

2023-01-31 11:57 UTC, istraka commented
Hi @LittleJohnII, I have addressed issue. See new commit.

2023-02-01 09:30 UTC, LittleJohnII commented on README.md
> +Sunstone support injection of several resources, i.e. hostname of resources (Azure Web app, AWS EC2 instance, ... ). The logic is that if you want to inject a particular field od particular type, you
This still stands, but it's not a problem worth another round. Resolving.

2023-02-01 09:33 UTC, LittleJohnII commented on Aws-README.md
> +Injection is based on field's type and annotation, for injecting hostname of a EC2 instance:
You lost an "is" here :).

2023-02-01 09:37 UTC, LittleJohnII commented on Aws-README.md
> +Injection is based on field's type and annotation, for injecting hostname of a EC2 instance:
I'll resolve this and put up a new comment, as this references an outdated code point.

2023-02-01 09:39 UTC, LittleJohnII approved these changes
There are three tiny comments left. None of them is a problem. Approved.

2023-02-01 09:39 UTC, LittleJohnII commented on AWS-README.md
> +Injection based on a field's type and annotation. For injecting the hostname of an EC2 instance:
"Injection is based"

2023-02-01 09:39 UTC, LittleJohnII commented on Azure-README.md
> +Injection based on a field's type and annotation. For injecting the hostname of a virtual machine:
"Injection is based"

2023-02-01 09:39 UTC, LittleJohnII commented on README.md
> +Sunstone support injection of several resources, i.e. hostname of resources (Azure Web app, AWS EC2 instance, ... ). The logic is that if you want to inject a particular field od particular type, you
"Sunstone supports"
And the previous point still stands - I think it would be better to have the example, starting from "I.e." on a new line.

2023-02-01 15:16 UTC, istraka commented on Azure-README.md
> +Injection based on a field's type and annotation. For injecting the hostname of a virtual machine:
fixed

2023-02-01 15:19 UTC, merged